### ISSUE TITLE
Support custom elements outside a template and bridge to web component technology. ~34

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-component#10]
From: https://github.com/canjs/canjs/issues/730

can.Component is designed as a bridge to upcoming [web component technology](http://www.w3.org/TR/components-intro/).  However, can.Component custom tags can only be used within a template.

I'd like to make can.Component's usable outside a template.  This issue is a place to discuss possible APIs, problems and solutions.  My thoughts are rough right now, but I'll be updating this post as ideas develop.

I'd like to support elements outside templates in the following scenarios:
### Modern browsers

In browsers that support [document.registerElement](http://www.w3.org/TR/2013/WD-custom-elements-20130514/#registering-custom-elements), we will automatically instantiate the component instance. For example:

``` js
can.Component.extend({
  tag: "panel"
  scope: {
    title: "@"
  },
  events: {
    inserted: function(){
      this.element.parent()[0].addPanel(this)
    }
  }
});

var panelElement = document.createElement("panel");

panelElement.setAttribute("title", "Recipes");

document.getElementsByTagName("tab")[0].appendChild(panelElement);
```
### Old Browsers

Older browsers will support custom elements through jQuery polyfills.  For example, with the same `panel` above, you could create and change its title:

``` js
var panel = $("<panel>");
panel.attr("title", "Recipes");

$("tab").append(panel);
```
## Complications

There are a lot of complications making can.Component work seamlessly outside a template.
### Scope

A custom `<slider>` element in a template might require an observable values passed to it like:

``` html
<slider value="progress" range-start="start" range-end="end"></slider>
```

where the scope has values like:

```
data = {
  progress: can.compute(0.5)
  start: can.compute(0),
  end: can.compute(1)
}
```

How would someone add these to a slider element outside  a template?  My suggestion:

**Modern browsers** - use properties to set values.

``` js
var slider = document.createElement("slider");
slider.progress = data.progress;
slider.start = data.start;
slider.end = data.end;
```

**Old Browsers** - use `.scope()`.

``` js
var slider = $("<slider>");
slider.scope(data)
```

Questions:
- How do we map the element properties to `.scope`?  
  - option: We can `Object.observe` on changes to the element and update the scope observable.
### Inner template and shadow dom

``` js
can.Component.extend({
  tag: "hello-world",
  template: "<h1><content/></h1>"
})
```

``` js
var hw = $("<hello-world>Hi There</hello-world>")
```

What does `h1.html()` look like?  What does setting `h1.html()` do?
### Mustache

How does the following work?

``` js
can.Component.extend({
  tag: "my-parent"
});

can.Component.extend({
  tag: "hello-world",
  template: "<h1>{{message}}</h1>"
})

var myparent = $("<my-parent></my-parent>")
var helloWorld = $("<hello-world></hello-world>");

myparent.append(helloWorld);

myparent.scope().attr("message", "Hi there");
```

What happens if `helloWorld` is detached?

**Comment by pYr0x** [comment]
dont know, but maybe the webcomponents polyfill can help http://webcomponents.org/polyfills/custom-elements/

**Comment by justinbmeyer** [comment]
I don't think that will help this problem.

**Comment by leoj3n** [comment]
What was being voted on? The "VOTE HERE" Bithub event link is down.

I do remember reading about something similar, related to scope outside of a template, when I was playing around with Polymer:

> Polymer's binding features are only available within templates that are managed by Polymer. As such, these features are available in templates used to define Polymer elements, for example, but not for elements placed directly in the main document.

> In order to use Polymer bindings without defining a new custom element, elements utilizing bindings may be wrapped with the dom-bind template extension. This template will immediately stamp itself into the main document and bind elements to the template itself as the binding scope.

https://www.polymer-project.org/1.0/docs/api/dom-bind

**Comment by matthewp** [comment]
@leoj3n this is an old issue migrated from canjs/canjs, things were very different 2 years ago :)

**Comment by leoj3n** [comment]
@matthewp Haha, okay ⌛ :fast_forward:

**Comment by matthewp** [comment]
Some discussion on gitter: https://gitter.im/canjs/canjs?at=57505c0c454cb2be09516841

Quoting @justinbmeyer from there:

> I don't think light dom view bindings would work

Why is it you think the view bindings would not work?  Your example is:

```handlebars
<my-component><x-foo ({^value}}="bar"></x-foo></my-component>
```

Where you're binding x-foo's value prop onto my-component's bar.  So, why do you say this won't work?

**Comment by matthewp** [comment]
I've started prototyping this here: https://github.com/matthewp/can-register-element

It relies on a bad hack to make sure it only calls init on elements it should. Would need a new API exposed by can-component to remove that (or just be built into can-component itself).

I'm interested in an answer to the above question so I can experiment a little more.

**Comment by pYr0x** [comment]
hey @matthewp, i tested your demo.. very good!

i have 2 comments:
1. i have to respect the order of creating `can.Component`. e.g.
```
Component.extend({
    tag: "demo-app",
    template: stache('{{message}} <demo-inside {message}="lala"></demo-inside>'),
    viewModel: {
      message: "hello me"
    }
  });
Component.extend({
    tag: "demo-inside",
    template: stache("<strong>{{message}}</strong>"),
    viewModel: {
      message: "not set"
    }
  });
```
with `<demo-app></demo-app>` will not work, because `demo-inside` is created after `demo-app`.

2. canjs binding is not working.
```
Component.extend({
    tag: "demo-inside",
    template: stache("<strong>{{message}}</strong>"),
    viewModel: {
      message: "not set"
    }
  });

  Component.extend({
    tag: "demo-app",
    template: stache('{{message}} <demo-inside {message}="message"></demo-inside>'),
    viewModel: {
      message: "hello me"
    }
  });
```
the template `<demo-inside {message}="message"></demo-inside>` will not pass `message` to the `demo-inside`

why do we need `Symbol`? what does this?

**Comment by matthewp** [comment]
Yeah, these are the types of problems that need to be worked out, the ordering is a big one. Part of me feels like this should be handled by module loading anyways; if you're nesting a component inside of another, then it should be a dependency.

I'm not sure about the bindings not working, might have to try it out.

> why do we need Symbol? what does this? it not supported by all browsers?

No, we don't need it, I can use can-util/dom/data instead, it's just for storing metadata.

**Comment by matthewp** [comment]
The more I think about it, the `<body>` shouldn't have a scope because it is not a template. The custom elements define their own data and pass this down to child components within their template (or through other means like the tabs example), so we don't have to worry about supporting bindings within the `<body>`.

**Comment by marshallswain** [comment]
Would this mean that we can't do a binding for a custom class on the body tag?

```
<body class="handy-css-scoping-class">
```

**Comment by matthewp** [comment]
So the issue is this, let's say you have a template like:

```html
<custom-el {foo}="bar">
  <nested-el {whatever}="something"></nested-el>
</custom-el>
```

In a template this will bind `foo` to the "bar" property in the scope (which is the map you provided to `render(new Map)`.  

Putting this directly in the html there is no longer a scope:


```html
<html>
<body>
<custom-el {foo}="bar">
  <nested-el {whatever}="something"></nested-el>
</custom-el>
</html>
</body>
```

The `<body>` and `<html>` elements don't have a scope. I wonder if the answer is to 

delay registering the elements (using document.registerElement / customElements.define) until after the user has called some kind of "ready" function ala route.ready():

```js
var customElements = require("can-custom-elements");

customElements.scope(document.body, new ViewModel());
customElements.ready();
```

Not saying this is the right API, but something like that.  Calling .ready() would go through and register each can-component with the native API.  The scope provided here would be the scope handed to the Component's tag handler.

**Comment by justinbmeyer** [comment]
Related: https://github.com/canjs/canjs/issues/2386

**Comment by matthewp** [comment]
cc @justinbmeyer and @pYr0x for feedback on this proposal: https://github.com/canjs/can-component/issues/10#issuecomment-232401997

Happy to move this to a new project if that makes sense (I think it does). I think this handles the root problem fairly well because registration is delayed until a root `scope` is provided for the page. Once a scope is provided each Component would be constructed with that scope.

**Comment by pYr0x** [comment]
1. i think it is a good idea, creating a new project.
2. do we really need a root VM? my thought is, why need a root component a parent scope? a component should get static props like 
```
<html>
<body>
<custom-el child-prop="foobar">
  <nested-el {whatever}="something"></nested-el>
</custom-el>
</html>
</body>
```
if some day we switch to nativ browser components, they also have no root scope?

**Comment by matthewp** [comment]
You don't have to have a root VM, no, but you usually do in CanJS applications. In your example, where do the values of `foobar` and `something` come from?  In my proposed API that could be provided:

```js
var ViewModel = DefineMap.extend({
  foobar: "string",
  something: "*"
});

var vm = new ViewModel({
  foobar: "qux",
  something: {}
});

customElements.scope(document.body, vm);
customElements.ready();
```

This is equivalent to how you do things by wiring up a template today.

**Comment by pYr0x** [comment]
- `foobar` is a primitive string (see http://canjs.com/docs/can.elementAndAttributes.html) 
- `something` is a property from the `custom-el` VM

**Comment by matthewp** [comment]
Yeah sorry, I didn't see that custom-el didn't have any bindings on its attributes.

`something` can't be a property on the custom-el VM. First that would require `leakScope` which is disabled by default. But even if custom-el had `leakScope: true`, that could still never work because custom-el is not what renders its children. It's not a subtemplate.

I think this is fine though, leakScope: false should be the norm, so the scope of the base page should be something that's setup initially (or not used at all).

**Comment by pYr0x** [comment]
but what is if we have a component like this:

```
can.Component({
    tag: "custom-el",
    template: "<content/>",
    ...
    ...
  });
```
this will render the `content` of the `custom-el` ?

**Comment by matthewp** [comment]
Yeah, we could detach the childNodes and give them to the component as the subtemplate. So when the custom-el renders (if using leakScope: true) it scope would then leak to the children.

**Comment by justinbmeyer** [comment]
This was added in 4.0
