### ISSUE TITLE
can-slot/can-template binding not working

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-component#198]
**Details:**

I'm trying to get can-slot to work. I'm passing some child components in the slot, and passing those components properties. I expected those properties to be passed from the can-slot parent component view model, and am unable to do so. I've tried several alterations of passing properties including using the binding syntax on the documentation, but can't seem to get it to work. 

**Demo:**

https://jsbin.com/bezugozira/edit?html,js,console,output

**Comment by chasenlehara** [comment]
Here’s my understanding of what’s going on:

`app-template` is rendered with `appViewModel`, which does not have a `myObject` property, which means that the default `can-template` is being rendered with an undefined `myObject`. Because the default slot is being rendered within the context of `home-page`, it does have `myObject`, and thus works as expected.

I think the key piece missing from that JS Bin is `<home-page myObject:to="myObject">`, which will take the default `myObject` from `home-page`, assign it to `appViewModel`, and then make it available to the `can-template`.

JS Bin: https://jsbin.com/necacajowa/1/edit?html,js,console,output

I don’t think this is a bug, but if I’ve missed something please reopen the issue. 😃

**Comment by chasenlehara** [comment]
Was just checking the docs to make sure my description matched what was documented, and realized that you could also add `this:from="this"` to the slot to get the same behavior (I think?): https://jsbin.com/xojoxoxeja/1/edit?html,js,console,output

**Comment by roemhildtg** [comment]
Yes, awesome, that jsbin example helps explain it a lot better! Thanks!
