### ISSUE TITLE
Error: You can't have two versions of can-dom-data-state

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-component#219]
this deponds on `can-dom-data-state`@1 and `can-util`, which in turn depends on `can-dom-data-state`@0.2.0

@m-mujica says @matthewp says we need to make it use `can-dom-data-state` directly.

```
├─┬ can-component@4.0.1
│ ├── can-dom-data-state@1.0.1 
│ └─┬ can-util@3.11.2
│   ├── can-dom-data-state@0.2.0
```

**Comment by matthewp** [comment]
The error is not coming from can-component. can-component doesn't use can-dom-data-state@0.2.0 either directly or indirectly.

Even though can-util depends on the old version, nothing should be importing it. You need to figure out what is importing can-util/dom/data/data (outside of can-util itself) to figure out where the problem is.

**Comment by christopherjbaker** [comment]
can-component uses [can-dom-data-state](https://github.com/canjs/can-component/blob/master/can-component.js#L30) and [can-util/dom/child-nodes](https://github.com/canjs/can-component/blob/master/can-component.js#L31)

I will see if I can find what is using `can-dom-data-state`, besides can-component.

**Comment by christopherjbaker** [comment]
For my project, I had a top level install of `can-dom-data-state` (left over from before it was fixed) that was causing de-duplication. Removing that and getting a fresh install fixed it for me.
